Repository bindhosts/bindhosts, pull requests merged in 2024-12, with the labels that each got.

#15 webui: pressing reboot prompt actually let's you reboot
  module/webroot/index.js
Labels: enhancement, webui, feature request

#19 webui: mode button triggers dev settings
  module/webroot/index.html
  module/webroot/index.js
Labels: webui

#22 webui/js: cut down cat to grep piping
  module/webroot/index.js
Labels: scripts, webui, optimization?

#28 Switch to toybox nproc
  module/bindhosts.sh
Labels: scripts

#31 workflows: execlude documentation changes from workflow trigger
  .github/workflows/release.yml
Labels: ci

#34 Documentation/sources: update bebasid description (again)
  Documentation/sources.md
Labels: documentation

#37 workflow: limit unnecessary steps
  .github/workflows/release.yml
Labels: ci
